name: Cask checks
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read
jobs:
  cask:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Add tap
        run: brew tap adeydas/notely "$GITHUB_WORKSPACE"
      - run: brew style --cask adeydas/notely/notely
      - run: brew audit --cask --online adeydas/notely/notely
      - run: brew livecheck --cask adeydas/notely/notely
      - run: brew fetch --cask adeydas/notely/notely
